DROP TABLE IF EXISTS EVENTS;

DROP TABLE IF EXISTS hibernate_sequence;
CREATE TABLE EVENTS (
  EVENT_ID       BIGINT       NOT NULL,
  DESCRIPTION    LONGTEXT,
  FINISH_DATE    DATETIME,
  EVENT_PRIORITY VARCHAR(255) NOT NULL,
  START_DATE     DATETIME     NOT NULL,
  EVENT_TITLE    VARCHAR(200) NOT NULL,
  PRIMARY KEY (EVENT_ID)
);

CREATE TABLE hibernate_sequence (
  next_val BIGINT
);

ALTER TABLE EVENTS
ADD CONSTRAINT UNIQUE_EVENT_TITLE_AND_START_DATE_PAIR UNIQUE (EVENT_TITLE, START_DATE);

INSERT INTO hibernate_sequence VALUES (13);

